# Generated by Django 6.0.5 on 2026-05-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='password',
            field=models.IntegerField(max_length=4),
        ),
    ]
