# Generated by Django 6.0.5 on 2026-05-26 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_alter_guestbook_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestbook',
            name='updated_at',
        ),
    ]
