# Generated by Django 6.0.5 on 2026-05-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0003_remove_guestbook_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
