# Generated by Django 6.0.5 on 2026-05-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0004_alter_guestbook_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='password',
            field=models.CharField(max_length=4),
        ),
    ]
