# Generated by Django 6.0.5 on 2026-05-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0005_alter_guestbook_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='writer',
            field=models.CharField(max_length=20),
        ),
    ]
