# Generated by Django 6.0.5 on 2026-05-31 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestbookLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('guestbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='guestbook.guestbook')),
            ],
            options={
                'unique_together': {('guestbook', 'ip')},
            },
        ),
    ]
