# Generated by Django 4.2 on 2026-05-31 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0008_guestbooklike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbooklike',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='guestbook.comment')),
            ],
            options={
                'unique_together': {('comment', 'ip')},
            },
        ),
    ]
