# Generated by Django 6.0.5 on 2026-05-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0009_alter_guestbooklike_id_commentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guestbooklike',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
